"""Generate a Markdown map of Euskera's public Python surface."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "euskera"
OUTPUT = ROOT / "docs" / "package-map.md"


@dataclass(frozen=True)
class Symbol:
    name: str
    line: int


@dataclass(frozen=True)
class Module:
    path: Path
    symbols: tuple[Symbol, ...]


def _assigned_names(node: ast.Assign | ast.AnnAssign) -> list[str]:
    targets = node.targets if isinstance(node, ast.Assign) else [node.target]
    names: list[str] = []
    for target in targets:
        if isinstance(target, ast.Name):
            names.append(target.id)
        elif isinstance(target, (ast.Tuple, ast.List)):
            names.extend(
                element.id
                for element in target.elts
                if isinstance(element, ast.Name)
            )
    return names


def _all_names(tree: ast.Module) -> set[str] | None:
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        names = _assigned_names(node)
        if "__all__" not in names:
            continue
        value = node.value
        if isinstance(value, (ast.List, ast.Tuple, ast.Set)):
            return {
                element.value
                for element in value.elts
                if isinstance(element, ast.Constant) and isinstance(element.value, str)
            }
        return set()
    return None


def public_symbols(source: str) -> tuple[Symbol, ...]:
    """Return public, locally defined top-level symbols from Python source."""

    tree = ast.parse(source)
    allowed = _all_names(tree)
    symbols: list[Symbol] = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom, ast.Expr)):
            continue
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names = [node.name]
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            names = _assigned_names(node)
        else:
            continue
        for name in names:
            if name.startswith("_") or (allowed is not None and name not in allowed):
                continue
            symbols.append(Symbol(name, node.lineno))
    return tuple(sorted(symbols, key=lambda symbol: (symbol.line, symbol.name)))


def collect_modules(package: Path = PACKAGE) -> tuple[Module, ...]:
    """Parse every package module, excluding cache directories."""

    modules: list[Module] = []
    for path in sorted(package.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        modules.append(Module(path, public_symbols(path.read_text(encoding="utf-8"))))
    return tuple(modules)


def _module_link(module: Module, root: Path) -> str:
    relative = module.path.relative_to(root).as_posix()
    target = Path("..") / relative
    return f"[`{relative}`]({target.as_posix()})"


def _directory_link(directory: Path, root: Path) -> str:
    relative = directory.relative_to(root).as_posix()
    return f"[`{relative}/`](../{relative}/)"


def render(
    modules: tuple[Module, ...],
    root: Path = ROOT,
    package: Path = PACKAGE,
) -> str:
    lines = [
        "# Package map",
        "",
        "<!-- Generated by `python scripts/generate_package_map.py`; do not edit manually. -->",
        "",
        "This navigable tree lists Python modules under `euskera/` and their "
        "public, locally defined top-level symbols. Imports and private names "
        "are intentionally omitted.",
        "",
        "## Modules and public symbols",
        "",
    ]
    by_path = {module.path: module for module in modules}

    def add_directory(directory: Path, depth: int) -> None:
        prefix = "  " * depth
        if directory != root:
            lines.append(f"{prefix}- {_directory_link(directory, root)}")
            depth += 1
            prefix = "  " * depth
        for path in sorted(directory.glob("*.py")):
            module = by_path.get(path)
            if module is None:
                continue
            lines.append(f"{prefix}- {_module_link(module, root)}")
            relative = module.path.relative_to(root).as_posix()
            target = (Path("..") / relative).as_posix()
            for symbol in module.symbols:
                lines.append(f"{prefix}  - [`{symbol.name}`]({target}#L{symbol.line})")
        for child in sorted(path for path in directory.iterdir() if path.is_dir()):
            if child.name == "__pycache__":
                continue
            add_directory(child, depth)

    add_directory(package, 0)
    return "\n".join(lines) + "\n"


def generate(output: Path = OUTPUT, package: Path = PACKAGE, root: Path = ROOT) -> str:
    content = render(collect_modules(package), root, package)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    return content


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the package map is stale",
    )
    args = parser.parse_args()
    expected = render(collect_modules(PACKAGE), ROOT)
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run this script without --check")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
